### ISSUE TITLE
No documentation on GitHub

### ISSUE THREAD

**Issue by daramarak** [skshetry/webdav4#120]
I think there should be documentation, but when clicking on ClientAPI in the readme of GitHub there is no documentation.

All that show is:

Client

.. automodule:: webdav4.client
    :show-inheritance:
    :members:

I guess this is not how it should be.

**Comment by skshetry** [comment]
Hi, @daramarak. It’s generated using sphinx from docstrings in the code: https://skshetry.github.io/webdav4/.

**Comment by daramarak** [comment]
Thank you, that link works perfect. But confusing that the link in github didnt. This is a great webdav library, i have tried 3 now, and your is definitely the best. Would be sad if people didn't use it because they couldn't find the documentation.

**Comment by skshetry** [comment]
Thank you for nice words.
The docs link is at the sidebar. Also, if you are not aware, this also has an fsspec-compatible filesystem, so the APIs work the same way in all the filesystems, s3, azure, google drive, google cloud storage, ssh and of course, webdav. 🙂

**Comment by skshetry** [comment]
Closing for now. Feel free to open new issue for bugs/feature requests. 🙂
