### ISSUE TITLE
Support: parse user/pass from URI?

### ISSUE THREAD

**Issue by pataquets** [skshetry/webdav4#171]
I'm trying to use the webdav4 lib initializing it with a full HTTP URI with user/pass built-in as:
`https://user:pass@myserver`.
Browsing at the docs and the code, I haven't seen this is supported. Is it possible?

If it's not, would it be a valid feature to accept a PR?

**Comment by skshetry** [comment]
Yes, you can pass the url directly as `base_url=` keyword argument either in `webdav4.fsspec.WebdavFileSystem` or in `webdav4.client.Client`.
