### ISSUE TITLE
[Feature Request] Support "Digest" authentication method

### ISSUE THREAD

**Issue by fleimgruber** [skshetry/webdav4#172]
I could not find any option to use "Digest" authentication instead of "Basic" authentication (http://www.webdav.org/specs/rfc2617.html).

**Comment by skshetry** [comment]
You can pass `auth=` to `Client` or `WebDAVFileSystem`.

```python
auth = httpx.DigestAuth("my_user", "password123")
client = Client(..., auth=auth)
# or,
fs = WebDAVFileSystem(..., auth=auth)
```

See [HTTPX Authentication](https://www.python-httpx.org/quickstart/#authentication). You can also implement custom flow if you need, see [Customizing Authentication - httpx](https://www.python-httpx.org/advanced/#customizing-authentication).

**Comment by fleimgruber** [comment]
Thanks for the quick answer and solution example, will test with that. Maybe the docs could contain a section with high-level aspects that are handled by dependencies? In any case, I think mentioning `httpx` somewhere would also catch a lot of people that are in skimming-mode to find a WebDAV library for their requirements.
