### ISSUE TITLE
Support self-signed certificates?

### ISSUE THREAD

**Issue by NePoCz** [skshetry/webdav4#49]
Hi, I am running a local webdav server and using a self-signed certificate. Would it be possible to support self-signed certificates in the CLI? Currently, I had to add "verify=False" to Client(base_url, auth=auth, **client_opts) in fsspec.py, but this is probably not the best solution as it disables certificate verification altogether. It works fine in my case, but I would consider it only a workaround

**Comment by skshetry** [comment]
In `fsspec`, this is already supported by passing `cert=/path/to/ca-certs/ca-bundle.crt`:
https://github.com/skshetry/webdav4/blob/81df05773636014132e20afa9be27152662b3064/src/webdav4/client.py#L251-L255

In CLI, as a workaround, you can specify the self-signed cert using the `SSL_CERT_FILE` environment variable.
eg: `SSL_CERT_FILE=/path/to/ca-certs/ca-bundle.crt`.

We could consider adding `--ssl-verify` that passes the `cert`. We could also look into supporting [fsspec's config](https://filesystem-spec.readthedocs.io/en/latest/features.html?highlight=config#configuration) but I haven't looked deeply into it.

**Comment by skshetry** [comment]
Closing for now, `SSL_CERT_FILE` is a good workaround. Though I am open to `--ssl-verify` flag in the CLI.
