### ISSUE TITLE
Pin depency versions with '>=' and '<' rather that with '=='

### ISSUE THREAD

**Issue by pauleikis** [skshetry/webdav4#87]
Great work on the library. Unfortunately it cannot be used as a library in a larger project due to a very strict version pinning as it is likely to produce conflicts with other dependencies.

I would suggest pinning library versions using broader requirements. 
For example, instead of `httpx==0.21.3` use `httpx>=0.21.3,<1.0.0`.

Are you ok with that? I could make the PR.

**Comment by skshetry** [comment]
Hi, thanks for creating an issue. I have been thinking of unpinning that but was never able to get to it. This was done at the time, as it seemed `httpx 1.0` was imminent: https://github.com/encode/httpx/pull/1797, but it hasn't happened yet.

Happy to take contributions, AFAIK this should be compatible `httpx>=0.20.0,<1`. Thanks. 🙂

**Comment by skshetry** [comment]
Closed by #88 and released in `0.9.4`.
